language: erlang
otp_release:
- 22.0
before_install:
- rebar3 local upgrade
- export PATH=~/.cache/rebar3/bin:$PATH
script:
- rebar3 ct --readable=false
- rebar3 compile
after_success:
- rebar3 as test coveralls send
